import 'dart:convert';
import 'dart:io';

import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';

/// Generates a Dart map containing bundled Markdown and MDX content.
final class DartEdgeDocsContentManifestGenerator {
  const DartEdgeDocsContentManifestGenerator();

  /// Writes a generated content manifest for [inputDirectory] to [outputFile].
  Future<File> writeManifest({
    required Directory inputDirectory,
    required File outputFile,
    required String constantName,
  }) async {
    final entries = <_ManifestEntry>[];
    await for (final entity in inputDirectory.list(
      recursive: true,
      followLinks: false,
    )) {
      if (entity is! File || !_isContentFile(entity)) {
        continue;
      }
      entries.add(
        _ManifestEntry(
          path: _relativePath(entity.uri, inputDirectory.uri),
          content: await entity.readAsString(),
        ),
      );
    }
    entries.sort((left, right) => left.path.compareTo(right.path));

    await outputFile.parent.create(recursive: true);
    await outputFile.writeAsString(_emitDart(constantName, entries));
    return outputFile;
  }
}

bool _isContentFile(File file) {
  return file.path.endsWith('.md') || file.path.endsWith('.mdx');
}

String _relativePath(Uri file, Uri root) {
  final rootPath = root.toFilePath(windows: false);
  final filePath = file.toFilePath(windows: false);
  return filePath.substring(rootPath.length).replaceAll(RegExp(r'^/+'), '');
}

String _emitDart(String constantName, List<_ManifestEntry> entries) {
  final manifest = literalMap(
    <Object?, Object?>{
      for (final entry in entries)
        _dartStringLiteral(entry.path): _dartStringLiteral(entry.content),
    },
    refer('String'),
    refer('String'),
  );
  final library = Library(
    (builder) => builder
      ..comments.addAll(const [
        'Generated by dart_edge_docs:generate_docs_manifest.',
        'Do not edit by hand.',
      ])
      ..body.add(
        Field(
          (field) => field
            ..name = constantName
            ..modifier = FieldModifier.constant
            ..assignment = manifest.code,
        ),
      ),
  );

  return _dartFormatter.format('${library.accept(_dartEmitter)}');
}

Expression _dartStringLiteral(String value) {
  var encoded = jsonEncode(value).replaceAll(r'$', r'\$');
  if (value.contains("'")) {
    return CodeExpression(Code(encoded));
  }

  encoded = encoded.substring(1, encoded.length - 1).replaceAll(r'\"', '"');
  return CodeExpression(Code("'$encoded'"));
}

final class _ManifestEntry {
  const _ManifestEntry({required this.path, required this.content});

  final String path;
  final String content;
}

final _dartEmitter = DartEmitter(useNullSafetySyntax: true);

final _dartFormatter = DartFormatter(
  languageVersion: DartFormatter.latestLanguageVersion,
);
