name: simple_test
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  dart_edge_http_server: ^0.1.0
  dart_edge_auth: ^0.1.0
  dart_edge_sql: ^0.1.0
  dart_edge_sql_migrator: ^0.1.0
  http: ^1.6.0


dev_dependencies:
  build_runner: ^2.10.0
  dart_edge_http_server_codegen: ^0.1.0
  dart_edge_sql_codegen: ^0.1.0
