name: simple_test
version: 0.1.0
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  dart_edge: ^0.1.0
  dart_edge_auth: ^0.1.0
  dart_edge_sql: ^0.1.0
  http: ^1.6.0


dev_dependencies:
  dart_edge_codegen: ^0.1.0
