name: dart_edge_sql_migrator
description: SQL migration manager for Dart Edge SQLite and PostgreSQL apps.
version: 0.3.10
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
repository: https://github.com/hipposphere/dart_edge/tree/main/packages/dart_edge_sql_migrator

environment:
  sdk: ">=3.11.0 <4.0.0"

resolution: workspace

dependencies:
  code_builder: ^4.11.1
  dart_edge_sql:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
    version: ^0.3.18
  dart_style: ^3.1.8
  data_assets: ^0.19.6

dev_dependencies:
  test: ^1.30.0
