name: dart_edge_ci
description: CI utilities for Dart Edge workspaces, including Docker image generation.
version: 0.1.11
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
repository: https://github.com/hipposphere/dart_edge/tree/main/packages/dart_edge_ci

executables:
  dart_edge_ci:

environment:
  sdk: ">=3.12.0 <4.0.0"

resolution: workspace

dependencies:
  args: ^2.7.0
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  test: ^1.30.0
