builders:
  dart_edge_http_server:
    import: "package:dart_edge_http_server_codegen/builder.dart"
    builder_factories: ["dartEdgeHttpServerBuilder"]
    build_extensions: {".dart": [".dart_edge_http_server.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
