// ignore_for_file: camel_case_types, non_constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;
import 'package:objective_c/objective_c.dart' as objc;
import 'package:ffi/ffi.dart' as pkg_ffi;

/// CWChannel
extension type CWChannel._(objc.ObjCObject object$)
    implements
        objc.ObjCObject,
        objc.NSObject,
        objc.NSCopying,
        objc.NSSecureCoding {
  /// Constructs a [CWChannel] that points to the same underlying object as [other].
  CWChannel.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal('CWChannel', macOS: (false, (10, 7, 0)));
    assert(isA(object$));
  }

  /// Constructs a [CWChannel] that wraps the given raw object pointer.
  CWChannel.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal('CWChannel', macOS: (false, (10, 7, 0)));
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [CWChannel].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_CWChannel,
  );
}

extension CWChannel$Methods on CWChannel {
  /// channelNumber
  int get channelNumber {
    objc.checkOsVersionInternal(
      'CWChannel.channelNumber',
      macOS: (false, (10, 7, 0)),
    );
    return _objc_msgSend_1hz7y9r(object$.ref.pointer, _sel_channelNumber);
  }
}

/// CWInterface
extension type CWInterface._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [CWInterface] that points to the same underlying object as [other].
  CWInterface.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal('CWInterface', macOS: (false, (10, 6, 0)));
    assert(isA(object$));
  }

  /// Constructs a [CWInterface] that wraps the given raw object pointer.
  CWInterface.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal('CWInterface', macOS: (false, (10, 6, 0)));
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [CWInterface].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_CWInterface,
  );
}

extension CWInterface$Methods on CWInterface {
  /// associateToNetwork:password:error:
  bool associateToNetwork(CWNetwork network, {objc.NSString? password}) {
    objc.checkOsVersionInternal(
      'CWInterface.associateToNetwork:password:error:',
      macOS: (false, (10, 7, 0)),
    );
    final $err = pkg_ffi.calloc<ffi.Pointer<objc.ObjCObjectImpl>>();
    try {
      final $ret = _objc_msgSend_6z4k82(
        object$.ref.pointer,
        _sel_associateToNetwork_password_error_,
        network.ref.pointer,
        password?.ref.pointer ?? ffi.nullptr,
        $err,
      );
      objc.NSErrorException.checkErrorPointer($err.value);
      return $ret;
    } finally {
      pkg_ffi.calloc.free($err);
    }
  }

  /// bssid
  objc.NSString? bssid() {
    objc.checkOsVersionInternal(
      'CWInterface.bssid',
      macOS: (false, (10, 6, 0)),
    );
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_bssid);
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// interfaceName
  objc.NSString? get interfaceName {
    objc.checkOsVersionInternal(
      'CWInterface.interfaceName',
      macOS: (false, (10, 7, 0)),
    );
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_interfaceName);
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// scanForNetworksWithName:error:
  objc.NSSet? scanForNetworksWithName(objc.NSString? networkName) {
    objc.checkOsVersionInternal(
      'CWInterface.scanForNetworksWithName:error:',
      macOS: (false, (10, 7, 0)),
    );
    final $err = pkg_ffi.calloc<ffi.Pointer<objc.ObjCObjectImpl>>();
    try {
      final $ret = _objc_msgSend_1lhpu4m(
        object$.ref.pointer,
        _sel_scanForNetworksWithName_error_,
        networkName?.ref.pointer ?? ffi.nullptr,
        $err,
      );
      objc.NSErrorException.checkErrorPointer($err.value);
      return $ret.address == 0
          ? null
          : objc.NSSet.fromPointer($ret, retain: true, release: true);
    } finally {
      pkg_ffi.calloc.free($err);
    }
  }

  /// scanForNetworksWithName:includeHidden:error:
  objc.NSSet? scanForNetworksWithName$1(
    objc.NSString? networkName, {
    required bool includeHidden,
  }) {
    objc.checkOsVersionInternal(
      'CWInterface.scanForNetworksWithName:includeHidden:error:',
      macOS: (false, (10, 13, 0)),
    );
    final $err = pkg_ffi.calloc<ffi.Pointer<objc.ObjCObjectImpl>>();
    try {
      final $ret = _objc_msgSend_13o59aq(
        object$.ref.pointer,
        _sel_scanForNetworksWithName_includeHidden_error_,
        networkName?.ref.pointer ?? ffi.nullptr,
        includeHidden,
        $err,
      );
      objc.NSErrorException.checkErrorPointer($err.value);
      return $ret.address == 0
          ? null
          : objc.NSSet.fromPointer($ret, retain: true, release: true);
    } finally {
      pkg_ffi.calloc.free($err);
    }
  }

  /// scanForNetworksWithSSID:error:
  objc.NSSet? scanForNetworksWithSSID(objc.NSData? ssid) {
    objc.checkOsVersionInternal(
      'CWInterface.scanForNetworksWithSSID:error:',
      macOS: (false, (10, 7, 0)),
    );
    final $err = pkg_ffi.calloc<ffi.Pointer<objc.ObjCObjectImpl>>();
    try {
      final $ret = _objc_msgSend_1lhpu4m(
        object$.ref.pointer,
        _sel_scanForNetworksWithSSID_error_,
        ssid?.ref.pointer ?? ffi.nullptr,
        $err,
      );
      objc.NSErrorException.checkErrorPointer($err.value);
      return $ret.address == 0
          ? null
          : objc.NSSet.fromPointer($ret, retain: true, release: true);
    } finally {
      pkg_ffi.calloc.free($err);
    }
  }

  /// scanForNetworksWithSSID:includeHidden:error:
  objc.NSSet? scanForNetworksWithSSID$1(
    objc.NSData? ssid, {
    required bool includeHidden,
  }) {
    objc.checkOsVersionInternal(
      'CWInterface.scanForNetworksWithSSID:includeHidden:error:',
      macOS: (false, (10, 13, 0)),
    );
    final $err = pkg_ffi.calloc<ffi.Pointer<objc.ObjCObjectImpl>>();
    try {
      final $ret = _objc_msgSend_13o59aq(
        object$.ref.pointer,
        _sel_scanForNetworksWithSSID_includeHidden_error_,
        ssid?.ref.pointer ?? ffi.nullptr,
        includeHidden,
        $err,
      );
      objc.NSErrorException.checkErrorPointer($err.value);
      return $ret.address == 0
          ? null
          : objc.NSSet.fromPointer($ret, retain: true, release: true);
    } finally {
      pkg_ffi.calloc.free($err);
    }
  }

  /// ssid
  objc.NSString? ssid() {
    objc.checkOsVersionInternal('CWInterface.ssid', macOS: (false, (10, 6, 0)));
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_ssid);
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }
}

/// CWNetwork
extension type CWNetwork._(objc.ObjCObject object$)
    implements
        objc.ObjCObject,
        objc.NSObject,
        objc.NSCopying,
        objc.NSSecureCoding {
  /// Constructs a [CWNetwork] that points to the same underlying object as [other].
  CWNetwork.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal('CWNetwork', macOS: (false, (10, 6, 0)));
    assert(isA(object$));
  }

  /// Constructs a [CWNetwork] that wraps the given raw object pointer.
  CWNetwork.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal('CWNetwork', macOS: (false, (10, 6, 0)));
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [CWNetwork].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_CWNetwork,
  );
}

extension CWNetwork$Methods on CWNetwork {
  /// bssid
  objc.NSString? get bssid {
    objc.checkOsVersionInternal('CWNetwork.bssid', macOS: (false, (10, 6, 0)));
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_bssid);
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// rssiValue
  int get rssiValue {
    objc.checkOsVersionInternal(
      'CWNetwork.rssiValue',
      macOS: (false, (10, 7, 0)),
    );
    return _objc_msgSend_1hz7y9r(object$.ref.pointer, _sel_rssiValue);
  }

  /// ssid
  objc.NSString? get ssid {
    objc.checkOsVersionInternal('CWNetwork.ssid', macOS: (false, (10, 6, 0)));
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_ssid);
    return $ret.address == 0
        ? null
        : objc.NSString.fromPointer($ret, retain: true, release: true);
  }

  /// supportsSecurity:
  bool supportsSecurity(CWSecurity security) {
    objc.checkOsVersionInternal(
      'CWNetwork.supportsSecurity:',
      macOS: (false, (10, 7, 0)),
    );
    return _objc_msgSend_r5hz5b(
      object$.ref.pointer,
      _sel_supportsSecurity_,
      security.value,
    );
  }

  /// wlanChannel
  CWChannel? get wlanChannel {
    objc.checkOsVersionInternal(
      'CWNetwork.wlanChannel',
      macOS: (false, (10, 7, 0)),
    );
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_wlanChannel);
    return $ret.address == 0
        ? null
        : CWChannel.fromPointer($ret, retain: true, release: true);
  }
}

enum CWSecurity {
  kCWSecurityNone(0),
  kCWSecurityWEP(1),
  kCWSecurityWPAPersonal(2),
  kCWSecurityWPAPersonalMixed(3),
  kCWSecurityWPA2Personal(4),
  kCWSecurityPersonal(5),
  kCWSecurityDynamicWEP(6),
  kCWSecurityWPAEnterprise(7),
  kCWSecurityWPAEnterpriseMixed(8),
  kCWSecurityWPA2Enterprise(9),
  kCWSecurityEnterprise(10),
  kCWSecurityWPA3Personal(11),
  kCWSecurityWPA3Enterprise(12),
  kCWSecurityWPA3Transition(13),
  kCWSecurityOWE(14),
  kCWSecurityOWETransition(15),
  kCWSecurityUnknown(9223372036854775807);

  final int value;
  const CWSecurity(this.value);

  static CWSecurity fromValue(int value) => switch (value) {
    0 => kCWSecurityNone,
    1 => kCWSecurityWEP,
    2 => kCWSecurityWPAPersonal,
    3 => kCWSecurityWPAPersonalMixed,
    4 => kCWSecurityWPA2Personal,
    5 => kCWSecurityPersonal,
    6 => kCWSecurityDynamicWEP,
    7 => kCWSecurityWPAEnterprise,
    8 => kCWSecurityWPAEnterpriseMixed,
    9 => kCWSecurityWPA2Enterprise,
    10 => kCWSecurityEnterprise,
    11 => kCWSecurityWPA3Personal,
    12 => kCWSecurityWPA3Enterprise,
    13 => kCWSecurityWPA3Transition,
    14 => kCWSecurityOWE,
    15 => kCWSecurityOWETransition,
    9223372036854775807 => kCWSecurityUnknown,
    _ => throw ArgumentError('Unknown value for CWSecurity: $value'),
  };
}

/// CWWiFiClient
extension type CWWiFiClient._(objc.ObjCObject object$)
    implements objc.ObjCObject, objc.NSObject {
  /// Constructs a [CWWiFiClient] that points to the same underlying object as [other].
  CWWiFiClient.as(objc.ObjCObject other) : object$ = other {
    objc.checkOsVersionInternal('CWWiFiClient', macOS: (false, (10, 10, 0)));
    assert(isA(object$));
  }

  /// Constructs a [CWWiFiClient] that wraps the given raw object pointer.
  CWWiFiClient.fromPointer(
    ffi.Pointer<objc.ObjCObjectImpl> other, {
    bool retain = false,
    bool release = false,
  }) : object$ = objc.ObjCObject(other, retain: retain, release: release) {
    objc.checkOsVersionInternal('CWWiFiClient', macOS: (false, (10, 10, 0)));
    assert(isA(object$));
  }

  /// Returns whether [obj] is an instance of [CWWiFiClient].
  static bool isA(objc.ObjCObject obj) => _objc_msgSend_19nvye5(
    obj.ref.pointer,
    _sel_isKindOfClass_,
    _class_CWWiFiClient,
  );

  /// sharedWiFiClient
  static CWWiFiClient sharedWiFiClient() {
    objc.checkOsVersionInternal(
      'CWWiFiClient.sharedWiFiClient',
      macOS: (false, (10, 10, 0)),
    );
    final $ret = _objc_msgSend_151sglz(
      _class_CWWiFiClient,
      _sel_sharedWiFiClient,
    );
    return CWWiFiClient.fromPointer($ret, retain: true, release: true);
  }
}

extension CWWiFiClient$Methods on CWWiFiClient {
  /// interface
  CWInterface? interface() {
    objc.checkOsVersionInternal(
      'CWWiFiClient.interface',
      macOS: (false, (10, 10, 0)),
    );
    final $ret = _objc_msgSend_151sglz(object$.ref.pointer, _sel_interface);
    return $ret.address == 0
        ? null
        : CWInterface.fromPointer($ret, retain: true, release: true);
  }

  /// interfaceWithName:
  CWInterface? interfaceWithName(objc.NSString? interfaceName) {
    objc.checkOsVersionInternal(
      'CWWiFiClient.interfaceWithName:',
      macOS: (false, (10, 10, 0)),
    );
    final $ret = _objc_msgSend_1sotr3r(
      object$.ref.pointer,
      _sel_interfaceWithName_,
      interfaceName?.ref.pointer ?? ffi.nullptr,
    );
    return $ret.address == 0
        ? null
        : CWInterface.fromPointer($ret, retain: true, release: true);
  }
}

late final _class_CWChannel = objc.getClass("CWChannel");
late final _class_CWInterface = objc.getClass("CWInterface");
late final _class_CWNetwork = objc.getClass("CWNetwork");
late final _class_CWWiFiClient = objc.getClass("CWWiFiClient");
final _objc_msgSend_13o59aq = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Bool,
          ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        bool,
        ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>>,
      )
    >();
final _objc_msgSend_151sglz = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_19nvye5 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_1hz7y9r = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Long Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
        )
      >
    >()
    .asFunction<
      int Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
      )
    >();
final _objc_msgSend_1lhpu4m = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>>,
      )
    >();
final _objc_msgSend_1sotr3r = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Pointer<objc.ObjCObjectImpl> Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
        )
      >
    >()
    .asFunction<
      ffi.Pointer<objc.ObjCObjectImpl> Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
      )
    >();
final _objc_msgSend_6z4k82 = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>>,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<ffi.Pointer<objc.ObjCObjectImpl>>,
      )
    >();
final _objc_msgSend_r5hz5b = objc.msgSendPointer
    .cast<
      ffi.NativeFunction<
        ffi.Bool Function(
          ffi.Pointer<objc.ObjCObjectImpl>,
          ffi.Pointer<objc.ObjCSelector>,
          ffi.Long,
        )
      >
    >()
    .asFunction<
      bool Function(
        ffi.Pointer<objc.ObjCObjectImpl>,
        ffi.Pointer<objc.ObjCSelector>,
        int,
      )
    >();
late final _sel_associateToNetwork_password_error_ = objc.registerName(
  "associateToNetwork:password:error:",
);
late final _sel_bssid = objc.registerName("bssid");
late final _sel_channelNumber = objc.registerName("channelNumber");
late final _sel_interface = objc.registerName("interface");
late final _sel_interfaceName = objc.registerName("interfaceName");
late final _sel_interfaceWithName_ = objc.registerName("interfaceWithName:");
late final _sel_isKindOfClass_ = objc.registerName("isKindOfClass:");
late final _sel_rssiValue = objc.registerName("rssiValue");
late final _sel_scanForNetworksWithName_error_ = objc.registerName(
  "scanForNetworksWithName:error:",
);
late final _sel_scanForNetworksWithName_includeHidden_error_ = objc
    .registerName("scanForNetworksWithName:includeHidden:error:");
late final _sel_scanForNetworksWithSSID_error_ = objc.registerName(
  "scanForNetworksWithSSID:error:",
);
late final _sel_scanForNetworksWithSSID_includeHidden_error_ = objc
    .registerName("scanForNetworksWithSSID:includeHidden:error:");
late final _sel_sharedWiFiClient = objc.registerName("sharedWiFiClient");
late final _sel_ssid = objc.registerName("ssid");
late final _sel_supportsSecurity_ = objc.registerName("supportsSecurity:");
late final _sel_wlanChannel = objc.registerName("wlanChannel");
