// ignore_for_file: camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

final class NativeBytes extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.IntPtr()
  external int len;
}

final class NativeOwnedBytes extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.IntPtr()
  external int len;
}

final class NativePair extends ffi.Struct {
  external NativeBytes key;

  external NativeBytes value;
}

final class NativeResult extends ffi.Struct {
  @ffi.Int32()
  external int status;

  external NativeBytes code;

  external NativeBytes message;
}

final class NativeString extends ffi.Struct {
  external NativeBytes bytes;
}
