import 'dart:typed_data';

/// Controls compact waveform generation during native audio conversion.
final class AudioWaveformSpec {
  const AudioWaveformSpec({
    this.baseInterval = const Duration(milliseconds: 10),
    this.levelFactors = const [1, 4, 16],
  });

  /// Duration represented by one min/max pair in the finest level.
  final Duration baseInterval;

  /// Multipliers used to derive progressively coarser levels.
  ///
  /// The list must contain `1` and contain unique, increasing positive values.
  final List<int> levelFactors;

  Map<String, Object?> toJson() => {
    'baseIntervalMicros': baseInterval.inMicroseconds,
    'levelFactors': levelFactors,
  };
}

/// Compact multi-resolution waveform generated by the native converter.
final class AudioWaveform {
  const AudioWaveform({required this.baseInterval, required this.levels});

  final Duration baseInterval;
  final List<AudioWaveformLevel> levels;

  factory AudioWaveform.fromJson(
    Map<String, Object?> json, {
    required Uint8List bytes,
  }) {
    final bufferOffset = bytes.offsetInBytes;
    return AudioWaveform(
      baseInterval: Duration(microseconds: json['baseIntervalMicros'] as int),
      levels: [
        for (final value in json['levels'] as List<Object?>)
          AudioWaveformLevel.fromJson(
            value as Map<String, Object?>,
            bytes: bytes,
            bufferOffset: bufferOffset,
          ),
      ],
    );
  }
}

/// One waveform resolution represented by interleaved signed min/max peaks.
final class AudioWaveformLevel {
  const AudioWaveformLevel({
    required this.interval,
    required this.factor,
    required this.peaks,
  });

  final Duration interval;
  final int factor;

  /// Signed interleaved `[min, max, min, max, ...]` amplitude values.
  final Int8List peaks;

  int get pointCount => peaks.length ~/ 2;

  factory AudioWaveformLevel.fromJson(
    Map<String, Object?> json, {
    required Uint8List bytes,
    required int bufferOffset,
  }) {
    final byteOffset = json['byteOffset'] as int;
    final byteLength = json['byteLength'] as int;
    if (byteOffset < 0 ||
        byteLength < 0 ||
        byteOffset + byteLength > bytes.length) {
      throw FormatException('Invalid native waveform level byte range.');
    }
    return AudioWaveformLevel(
      interval: Duration(microseconds: json['intervalMicros'] as int),
      factor: json['factor'] as int,
      peaks: Int8List.view(bytes.buffer, bufferOffset + byteOffset, byteLength),
    );
  }
}
