name: dart_edge_core
description: Transport-agnostic core contracts for Dart Edge.
version: 0.3.39
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
repository: https://github.com/hipposphere/dart_edge/tree/main/packages/dart_edge_core

environment:
  sdk: ">=3.12.0 <4.0.0"

resolution: workspace

dependencies:
  json_schema:
    hosted: https://pub.hippolabs.org
    version: ^0.1.2

dev_dependencies:
  ffigen: ^20.1.1
  test: ^1.30.0
