name: dart_edge_auth_db_benchmark_dart_edge_http_server
description: Dart Edge target for the auth/db HTTP benchmark suite.
publish_to: none
version: 0.2.1

environment:
  sdk: ">=3.11.0 <4.0.0"

resolution: workspace

dependencies:
  dart_edge_auth_db_benchmark_shared: any
  dart_edge_http_server:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
  dart_edge_auth:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
  dart_edge_s3_client:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
  dart_edge_sql:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
