name: simple_test_db_models
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  dart_edge_core:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"

dev_dependencies:
  dart_edge_http_server_codegen: 
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"