name: simple_test_client
version: 0.1.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  dart_edge_core:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
  dart_edge_http_client:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
  simple_test_db_models:
    path: ../simple_test_db_models
  hippo_auth_backend:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
