// ignore_for_file: camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset(
  'package:dart_edge_http_server_runtime/dart_edge_http_server_runtime.dart',
)
library;

import 'dart:ffi' as ffi;
import 'package:dart_edge_native_bridge/dart_edge_native_bridge.dart' as imp$1;

@ffi.Native<
  ffi.Bool Function(ffi.Int64, ffi.IntPtr, ffi.Pointer<imp$1.NativePair>)
>()
external bool dart_edge_http_server_runtime_accept_web_socket(
  int request_id,
  int header_count,
  ffi.Pointer<imp$1.NativePair> headers,
);

@ffi.Native<
  ffi.Bool Function(ffi.Int64, ffi.IntPtr, ffi.Pointer<imp$1.NativePair>)
>()
external bool dart_edge_http_server_runtime_accept_web_transport(
  int request_id,
  int header_count,
  ffi.Pointer<imp$1.NativePair> headers,
);

@ffi.Native<ffi.Bool Function(ffi.Int64)>()
external bool dart_edge_http_server_runtime_finish_binary_stream_response(
  int request_id,
);

@ffi.Native<ffi.Bool Function(ffi.Int64)>()
external bool dart_edge_http_server_runtime_finish_sse_response(int request_id);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeMultipartForm>)>(isLeaf: true)
external void dart_edge_http_server_runtime_free_multipart_form(
  ffi.Pointer<NativeMultipartForm> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeTransportRequest>)>(
  isLeaf: true,
)
external void dart_edge_http_server_runtime_free_request(
  ffi.Pointer<NativeTransportRequest> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>(isLeaf: true)
external void dart_edge_http_server_runtime_free_string(
  ffi.Pointer<ffi.Char> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeWebSocketConnection>)>(
  isLeaf: true,
)
external void dart_edge_http_server_runtime_free_web_socket_connection(
  ffi.Pointer<NativeWebSocketConnection> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeWebSocketMessage>)>(
  isLeaf: true,
)
external void dart_edge_http_server_runtime_free_web_socket_message(
  ffi.Pointer<NativeWebSocketMessage> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeWebTransportConnection>)>()
external void dart_edge_http_server_runtime_free_web_transport_connection(
  ffi.Pointer<NativeWebTransportConnection> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeWebTransportDatagram>)>()
external void dart_edge_http_server_runtime_free_web_transport_datagram(
  ffi.Pointer<NativeWebTransportDatagram> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeWebTransportOperation>)>()
external void dart_edge_http_server_runtime_free_web_transport_operation(
  ffi.Pointer<NativeWebTransportOperation> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeWebTransportStream>)>()
external void dart_edge_http_server_runtime_free_web_transport_stream(
  ffi.Pointer<NativeWebTransportStream> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeWebTransportStreamChunk>)>()
external void dart_edge_http_server_runtime_free_web_transport_stream_chunk(
  ffi.Pointer<NativeWebTransportStreamChunk> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeWebTransportStreamInfo>)>()
external void dart_edge_http_server_runtime_free_web_transport_stream_info(
  ffi.Pointer<NativeWebTransportStreamInfo> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeWebTransportStreamTerminal>)>()
external void dart_edge_http_server_runtime_free_web_transport_stream_terminal(
  ffi.Pointer<NativeWebTransportStreamTerminal> value,
);

@ffi.Native<ffi.Int32 Function()>(isLeaf: true)
external int dart_edge_http_server_runtime_native_abi_version();

@ffi.Native<
  ffi.Pointer<NativeMultipartForm> Function(
    ffi.Pointer<NativeTransportRequest>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<NativeMultipartForm>
dart_edge_http_server_runtime_parse_multipart(
  ffi.Pointer<NativeTransportRequest> request,
  ffi.Pointer<ffi.Char> content_type,
);

@ffi.Native<ffi.Bool Function(ffi.Int64, imp$1.NativeBytes)>()
external bool dart_edge_http_server_runtime_send_binary_stream_chunk(
  int request_id,
  imp$1.NativeBytes chunk,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Int64,
    ffi.Int32,
    ffi.Pointer<ffi.Char>,
    imp$1.NativeBytes,
    ffi.IntPtr,
    ffi.Pointer<imp$1.NativePair>,
  )
>()
external bool dart_edge_http_server_runtime_send_response(
  int request_id,
  int status,
  ffi.Pointer<ffi.Char> content_type,
  imp$1.NativeBytes body,
  int header_count,
  ffi.Pointer<imp$1.NativePair> headers,
);

@ffi.Native<ffi.Bool Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external bool dart_edge_http_server_runtime_send_sse_chunk(
  int request_id,
  ffi.Pointer<ffi.Char> chunk,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Int64,
    ffi.Int32,
    ffi.Pointer<ffi.Char>,
    ffi.Int64,
    ffi.IntPtr,
    ffi.Pointer<imp$1.NativePair>,
  )
>()
external bool dart_edge_http_server_runtime_start_binary_stream_response(
  int request_id,
  int status,
  ffi.Pointer<ffi.Char> content_type,
  int content_length,
  int header_count,
  ffi.Pointer<imp$1.NativePair> headers,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Int64,
    ffi.Int32,
    ffi.Pointer<ffi.Char>,
    ffi.Int64,
    ffi.IntPtr,
    ffi.Pointer<imp$1.NativePair>,
    ffi.Pointer<imp$1.NativeByteStream>,
  )
>()
external bool dart_edge_http_server_runtime_start_native_binary_stream_response(
  int request_id,
  int status,
  ffi.Pointer<ffi.Char> content_type,
  int content_length,
  int header_count,
  ffi.Pointer<imp$1.NativePair> headers,
  ffi.Pointer<imp$1.NativeByteStream> stream,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Int64,
    ffi.Int64,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    dart_edge_http_server_runtime_transport_event_callback_t,
  )
>()
external int dart_edge_http_server_runtime_start_server(
  ffi.Pointer<ffi.Char> host,
  int port,
  int worker_count,
  ffi.Pointer<ffi.Char> routes_json,
  ffi.Pointer<ffi.Char> middlewares_json,
  dart_edge_http_server_runtime_transport_event_callback_t callback,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Int64,
    ffi.Int32,
    ffi.IntPtr,
    ffi.Pointer<imp$1.NativePair>,
  )
>()
external bool dart_edge_http_server_runtime_start_sse_response(
  int request_id,
  int status,
  int header_count,
  ffi.Pointer<imp$1.NativePair> headers,
);

@ffi.Native<ffi.Void Function()>()
external void dart_edge_http_server_runtime_stop_server();

@ffi.Native<ffi.Void Function(ffi.Int64)>()
external void dart_edge_http_server_runtime_stop_server_by_id(int server_id);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> dart_edge_http_server_runtime_take_last_error();

@ffi.Native<ffi.Pointer<NativeTransportRequest> Function(ffi.Int64)>()
external ffi.Pointer<NativeTransportRequest>
dart_edge_http_server_runtime_take_request(int request_id);

@ffi.Native<ffi.Pointer<NativeWebSocketConnection> Function(ffi.Int64)>()
external ffi.Pointer<NativeWebSocketConnection>
dart_edge_http_server_runtime_take_web_socket_connection(int session_id);

@ffi.Native<ffi.Pointer<NativeWebSocketMessage> Function(ffi.Int64)>()
external ffi.Pointer<NativeWebSocketMessage>
dart_edge_http_server_runtime_take_web_socket_message(int session_id);

@ffi.Native<ffi.Pointer<NativeWebTransportConnection> Function(ffi.Int64)>()
external ffi.Pointer<NativeWebTransportConnection>
dart_edge_http_server_runtime_take_web_transport_connection(int session_id);

@ffi.Native<ffi.Pointer<NativeWebTransportDatagram> Function(ffi.Int64)>()
external ffi.Pointer<NativeWebTransportDatagram>
dart_edge_http_server_runtime_take_web_transport_datagram(int session_id);

@ffi.Native<ffi.Pointer<NativeWebTransportOperation> Function(ffi.Int64)>()
external ffi.Pointer<NativeWebTransportOperation>
dart_edge_http_server_runtime_take_web_transport_operation(int operation_id);

@ffi.Native<ffi.Pointer<NativeWebTransportStream> Function(ffi.Int64)>()
external ffi.Pointer<NativeWebTransportStream>
dart_edge_http_server_runtime_take_web_transport_stream(int session_id);

@ffi.Native<ffi.Pointer<NativeWebTransportStreamChunk> Function(ffi.Int64)>()
external ffi.Pointer<NativeWebTransportStreamChunk>
dart_edge_http_server_runtime_take_web_transport_stream_chunk(int stream_id);

@ffi.Native<ffi.Pointer<NativeWebTransportStreamInfo> Function(ffi.Int64)>()
external ffi.Pointer<NativeWebTransportStreamInfo>
dart_edge_http_server_runtime_take_web_transport_stream_info(int stream_id);

@ffi.Native<ffi.Pointer<NativeWebTransportStreamTerminal> Function(ffi.Int64)>()
external ffi.Pointer<NativeWebTransportStreamTerminal>
dart_edge_http_server_runtime_take_web_transport_stream_terminal(int stream_id);

@ffi.Native<ffi.Bool Function(ffi.Int64, ffi.Int32, ffi.Pointer<ffi.Char>)>()
external bool dart_edge_http_server_runtime_web_socket_close(
  int session_id,
  int code,
  ffi.Pointer<ffi.Char> reason,
);

@ffi.Native<ffi.Bool Function(ffi.Int64, imp$1.NativeBytes)>()
external bool dart_edge_http_server_runtime_web_socket_send_binary(
  int session_id,
  imp$1.NativeBytes body,
);

@ffi.Native<ffi.Bool Function(ffi.Int64, ffi.Pointer<ffi.Char>)>()
external bool dart_edge_http_server_runtime_web_socket_send_text(
  int session_id,
  ffi.Pointer<ffi.Char> text,
);

@ffi.Native<ffi.Bool Function(ffi.Int64, ffi.Int32, ffi.Pointer<ffi.Char>)>()
external bool dart_edge_http_server_runtime_web_transport_close(
  int session_id,
  int code,
  ffi.Pointer<ffi.Char> reason,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int
dart_edge_http_server_runtime_web_transport_open_bidirectional_stream(
  int session_id,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int
dart_edge_http_server_runtime_web_transport_open_unidirectional_stream(
  int session_id,
);

@ffi.Native<ffi.Bool Function(ffi.Int64, imp$1.NativeBytes)>()
external bool dart_edge_http_server_runtime_web_transport_send_datagram(
  int session_id,
  imp$1.NativeBytes body,
);

@ffi.Native<ffi.Bool Function(ffi.Int64, imp$1.NativeBytes)>()
external bool dart_edge_http_server_runtime_web_transport_send_stream(
  int session_id,
  imp$1.NativeBytes body,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64)>()
external int dart_edge_http_server_runtime_web_transport_stream_finish(
  int stream_id,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Uint32)>()
external int dart_edge_http_server_runtime_web_transport_stream_reset(
  int stream_id,
  int error_code,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, ffi.Uint32)>()
external int dart_edge_http_server_runtime_web_transport_stream_stop(
  int stream_id,
  int error_code,
);

@ffi.Native<ffi.Int64 Function(ffi.Int64, imp$1.NativeBytes)>()
external int dart_edge_http_server_runtime_web_transport_stream_write(
  int stream_id,
  imp$1.NativeBytes body,
);

final class NativeHttpRequest extends ffi.Struct {
  @ffi.Int32()
  external int method;

  external ffi.Pointer<ffi.Char> path;

  @ffi.IntPtr()
  external int query_count;

  external ffi.Pointer<imp$1.NativePair> query;

  @ffi.IntPtr()
  external int header_count;

  external ffi.Pointer<imp$1.NativePair> headers;

  external imp$1.NativeBytes body;
}

final class NativeHttpResponse extends ffi.Struct {
  @ffi.Uint16()
  external int status;

  external imp$1.NativeBytes content_type;

  @ffi.IntPtr()
  external int header_count;

  external ffi.Pointer<imp$1.NativePair> headers;

  external imp$1.NativeBytes body;
}

final class NativeMultipartField extends ffi.Struct {
  external imp$1.NativeBytes name;

  external imp$1.NativeBytes value;
}

final class NativeMultipartFile extends ffi.Struct {
  external imp$1.NativeBytes field_name;

  external imp$1.NativeBytes filename;

  external imp$1.NativeBytes content_type;

  external imp$1.NativeBytes body;
}

final class NativeMultipartForm extends ffi.Struct {
  @ffi.IntPtr()
  external int field_count;

  external ffi.Pointer<NativeMultipartField> fields;

  @ffi.IntPtr()
  external int file_count;

  external ffi.Pointer<NativeMultipartFile> files;
}

final class NativeTransportRequest extends ffi.Struct {
  external imp$1.NativeBytes route_id;

  @ffi.IntPtr()
  external int path_param_count;

  external ffi.Pointer<imp$1.NativePair> path_params;

  @ffi.IntPtr()
  external int query_count;

  external ffi.Pointer<imp$1.NativePair> query;

  @ffi.IntPtr()
  external int header_count;

  external ffi.Pointer<imp$1.NativePair> headers;

  external imp$1.NativeBytes body;

  @ffi.Uint8()
  external int request_kind;

  @ffi.Uint8()
  external int body_kind;
}

final class NativeWebSocketConnection extends ffi.Struct {
  @ffi.Int64()
  external int session_id;

  @ffi.Int64()
  external int request_id;

  external imp$1.NativeBytes route_id;

  @ffi.IntPtr()
  external int path_param_count;

  external ffi.Pointer<imp$1.NativePair> path_params;

  @ffi.IntPtr()
  external int query_count;

  external ffi.Pointer<imp$1.NativePair> query;

  @ffi.IntPtr()
  external int header_count;

  external ffi.Pointer<imp$1.NativePair> headers;
}

final class NativeWebSocketMessage extends ffi.Struct {
  @ffi.Int64()
  external int session_id;

  @ffi.Uint8()
  external int kind;

  external imp$1.NativeBytes body;
}

final class NativeWebTransportConnection extends ffi.Struct {
  @ffi.Int64()
  external int session_id;

  @ffi.Int64()
  external int request_id;

  external imp$1.NativeBytes route_id;

  @ffi.IntPtr()
  external int path_param_count;

  external ffi.Pointer<imp$1.NativePair> path_params;

  @ffi.IntPtr()
  external int query_count;

  external ffi.Pointer<imp$1.NativePair> query;

  @ffi.IntPtr()
  external int header_count;

  external ffi.Pointer<imp$1.NativePair> headers;
}

final class NativeWebTransportDatagram extends ffi.Struct {
  @ffi.Int64()
  external int session_id;

  external imp$1.NativeBytes body;
}

final class NativeWebTransportOperation extends ffi.Struct {
  @ffi.Int64()
  external int operation_id;

  @ffi.Int64()
  external int session_id;

  @ffi.Int64()
  external int stream_id;

  @ffi.Int64()
  external int protocol_id;

  @ffi.Uint8()
  external int kind;

  @ffi.Bool()
  external bool succeeded;

  external imp$1.NativeBytes error;
}

final class NativeWebTransportStream extends ffi.Struct {
  @ffi.Int64()
  external int session_id;

  external imp$1.NativeBytes body;
}

final class NativeWebTransportStreamChunk extends ffi.Struct {
  @ffi.Int64()
  external int stream_id;

  external imp$1.NativeBytes body;
}

final class NativeWebTransportStreamInfo extends ffi.Struct {
  @ffi.Int64()
  external int session_id;

  @ffi.Int64()
  external int stream_id;

  @ffi.Int64()
  external int protocol_id;

  @ffi.Uint8()
  external int kind;
}

final class NativeWebTransportStreamTerminal extends ffi.Struct {
  @ffi.Int64()
  external int stream_id;

  @ffi.Int64()
  external int error_code;

  external imp$1.NativeBytes error;
}

typedef dart_edge_http_server_runtime_transport_event_callback_t =
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(ffi.Int32 event_kind, ffi.Int64 event_id)
      >
    >;
