name: dart_edge_better_auth
description: Pure Dart Better Auth-compatible authentication routes for Dart Edge.
version: 0.1.4
# publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
publish_to: none
repository: https://github.com/hipposphere/dart_edge/tree/main/packages/dart_edge_better_auth

environment:
  sdk: ">=3.12.0 <4.0.0"

resolution: workspace

dependencies:
  crypto: ^3.0.7
  dart_edge_core:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
    version: ^0.3.31
  dart_edge_sql:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
    version: ^0.3.30
  dart_edge_sql_migrator:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
    version: ^0.3.17
  json_schema:
    hosted: https://pub.hippolabs.org
    version: ^0.1.1
  pointycastle: ^4.0.0

dev_dependencies:
  dart_edge_sql_codegen:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
    version: ^0.3.39
  dart_edge_http_server:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
    version: ^0.3.16
  dart_edge_sql_pglite: ^0.1.13
  test: ^1.30.0
