import 'dart:io';

import 'package:dart_edge_sql/dart_edge_sql.dart';
import 'package:dart_edge_sql_codegen/dart_edge_sql_codegen.dart';

const _schemaPath =
    'rust/vendor/better-auth-diesel-sqlite/migrations/'
    '00000000000000_create_auth_tables/up.sql';

Future<void> main() async {
  final schema = File(_schemaPath).readAsStringSync();
  final database = await _introspectBetterAuthSchema(schema);

  final outputs = <String, String>{
    'lib/src/generated/model_helpers.g.dart': _modelHelpers,
    'lib/src/generated/schema.g.dart': _schema,
    'lib/src/generated/models/user.g.dart': _userModel,
    'lib/src/generated/models/session.g.dart': _sessionModel,
    'lib/src/generated/tables.g.dart': _emitTables(database),
  };

  for (final entry in outputs.entries) {
    final file = File(entry.key)..parent.createSync(recursive: true);
    file.writeAsStringSync(entry.value);
  }
}

Future<IntrospectedDatabase> _introspectBetterAuthSchema(String schema) async {
  final database = SqliteDatabase.inMemory();
  try {
    await database.execute(sql(schema));
    final introspected = await SqliteIntrospector.fromDatabase(
      database,
      includeTables: const {'users', 'sessions'},
    ).introspect();
    return introspected;
  } finally {
    await database.close();
  }
}

String _emitTables(IntrospectedDatabase database) {
  return emitDartTableDescriptorLibrary(
    database,
    partOf: '../dart_edge_auth.dart',
    schemaClassName: 'DartEdgeAuthSchema',
    naming: DartSchemaNaming(modelNameBuilder: _authModelName),
  );
}

String _authModelName(DartSchemaModelNameContext context) {
  final tablePrefix = switch (context.tableName) {
    'users' => 'DartEdgeAuthUser',
    'sessions' => 'DartEdgeAuthSession',
    final table => throw StateError('Unsupported Better Auth table "$table".'),
  };
  return switch (context.kind) {
    DartSchemaModelKind.row => tablePrefix,
    DartSchemaModelKind.insert => 'Map<String, Object?>',
    DartSchemaModelKind.update => 'Map<String, Object?>',
    DartSchemaModelKind.table => '${tablePrefix}sTable',
  };
}

const _modelHelpers = r'''
// Generated by tool/generate_auth_models.dart from the Better Auth SQL schema.
// Do not edit by hand.

part of '../dart_edge_auth.dart';

Object? _authJsonLookup(Map<String, Object?> json, String key, [String? alt]) {
  if (json.containsKey(key)) {
    return json[key];
  }
  if (alt != null && json.containsKey(alt)) {
    return json[alt];
  }
  return null;
}

String _authRequiredString(
  Map<String, Object?> json,
  String key, [
  String? alt,
]) {
  final value = _authJsonLookup(json, key, alt);
  if (value is String) {
    return value;
  }
  throw StateError('Auth JSON field "$key" is not a string.');
}

String? _authString(Map<String, Object?> json, String key, [String? alt]) {
  final value = _authJsonLookup(json, key, alt);
  if (value == null) {
    return null;
  }
  if (value is String) {
    return value;
  }
  throw StateError('Auth JSON field "$key" is not a string.');
}

bool _authBool(
  Map<String, Object?> json,
  String key, {
  String? fallbackKey,
  bool defaultValue = false,
}) {
  final value = _authJsonLookup(json, key, fallbackKey);
  return _authBoolValue(value, defaultValue: defaultValue);
}

bool _authBoolValue(Object? value, {bool defaultValue = false}) {
  return switch (value) {
    null => defaultValue,
    final bool boolValue => boolValue,
    final num number => number != 0,
    final String text => text == '1' || text.toLowerCase() == 'true',
    _ => throw StateError('Auth value "$value" is not a boolean.'),
  };
}

DateTime _authRequiredDateTime(
  Map<String, Object?> json,
  String key, {
  String? fallbackKey,
}) {
  final value = _authJsonLookup(json, key, fallbackKey);
  return _authRequiredDateTimeValue(value);
}

DateTime _authRequiredDateTimeValue(Object? value) {
  final parsed = _authDateTimeValue(value);
  if (parsed == null) {
    throw StateError('Auth date-time value is missing.');
  }
  return parsed;
}

DateTime? _authDateTime(
  Map<String, Object?> json,
  String key, {
  String? fallbackKey,
}) {
  return _authDateTimeValue(_authJsonLookup(json, key, fallbackKey));
}

DateTime? _authDateTimeValue(Object? value) {
  return switch (value) {
    null => null,
    final DateTime dateTime => dateTime,
    final String text when text.isEmpty => null,
    final String text => DateTime.parse(text),
    _ => throw StateError('Auth value "$value" is not a date-time.'),
  };
}

Object? _authJsonValue(Object? value) {
  if (value is String) {
    final trimmed = value.trimLeft();
    if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
      return jsonDecode(value);
    }
  }
  return value;
}

Object? _authJsonColumn(Object? value) {
  if (value == null || value is String) {
    return value;
  }
  return jsonEncode(value);
}
''';

const _schema = r'''
// Generated by tool/generate_auth_models.dart from the Better Auth SQL schema.
// Do not edit by hand.

part of '../dart_edge_auth.dart';

/// Generated model, route result schema, and table descriptors for Better Auth.
final class DartEdgeAuthSchema {
  const DartEdgeAuthSchema({this.databaseSchema});
  const DartEdgeAuthSchema._() : databaseSchema = null;

  /// Optional database schema that contains the Better Auth tables.
  final String? databaseSchema;

  static const users = DartEdgeAuthUsersTable.table;
  static const sessions = DartEdgeAuthSessionsTable.table;

  static const List<JsonSchema> modelSchemas = <JsonSchema>[
    DartEdgeAuthUser.jsonSchema,
    DartEdgeAuthSession.jsonSchema,
  ];

  static const List<JsonSchema> resultSchemas = <JsonSchema>[
    DartEdgeAuthSignUpResult.jsonSchema,
    DartEdgeAuthSignInResult.jsonSchema,
    DartEdgeAuthSessionResult.jsonSchema,
    DartEdgeAuthUserResult.jsonSchema,
    DartEdgeAuthSessionUserResult.jsonSchema,
    DartEdgeAuthListUsersResult.jsonSchema,
    DartEdgeAuthListSessionsResult.jsonSchema,
    DartEdgeAuthStatusResult.jsonSchema,
    DartEdgeAuthSuccessResult.jsonSchema,
    DartEdgeAuthPermissionResult.jsonSchema,
  ];

  static const List<JsonSchema> schemas = <JsonSchema>[
    ...modelSchemas,
    ...resultSchemas,
  ];

  static const JsonSchemaRegistry jsonSchemas = JsonSchemaRegistry(
    schemas: schemas,
  );
}
''';

const _userModel = r'''
// Generated by tool/generate_auth_models.dart from the Better Auth SQL schema.
// Do not edit by hand.

part of '../../dart_edge_auth.dart';

/// Row model for the Better Auth `users` table.
final class DartEdgeAuthUser implements JsonEncodable {
  const DartEdgeAuthUser({
    required this.id,
    required this.name,
    required this.email,
    required this.username,
    required this.displayUsername,
    required this.emailVerified,
    required this.image,
    required this.role,
    required this.banned,
    required this.banReason,
    required this.banExpires,
    required this.twoFactorEnabled,
    required this.metadata,
    required this.createdAt,
    required this.updatedAt,
  });

  factory DartEdgeAuthUser.fromSqlRow(SqlRow row, {String prefix = ''}) {
    return DartEdgeAuthUser(
      id: row.read<String>('${prefix}id'),
      name: row.readNullable<String>('${prefix}name'),
      email: row.readNullable<String>('${prefix}email'),
      username: row.readNullable<String>('${prefix}username'),
      displayUsername: row.readNullable<String>('${prefix}display_username'),
      emailVerified: _authBoolValue(row['${prefix}email_verified']),
      image: row.readNullable<String>('${prefix}image'),
      role: row.readNullable<String>('${prefix}role'),
      banned: _authBoolValue(row['${prefix}banned']),
      banReason: row.readNullable<String>('${prefix}ban_reason'),
      banExpires: _authDateTimeValue(row['${prefix}ban_expires']),
      twoFactorEnabled: _authBoolValue(row['${prefix}two_factor_enabled']),
      metadata: _authJsonValue(row['${prefix}metadata']),
      createdAt: _authRequiredDateTimeValue(row['${prefix}created_at']),
      updatedAt: _authRequiredDateTimeValue(row['${prefix}updated_at']),
    );
  }

  factory DartEdgeAuthUser.fromColumns(
    Map<String, Object?> columns, {
    String prefix = '',
  }) => DartEdgeAuthUser.fromSqlRow(SqlRow(columns), prefix: prefix);

  factory DartEdgeAuthUser.fromJson(Map<String, Object?> json) {
    return DartEdgeAuthUser(
      id: _authRequiredString(json, 'id'),
      name: _authString(json, 'name'),
      email: _authString(json, 'email'),
      username: _authString(json, 'username'),
      displayUsername: _authString(json, 'displayUsername', 'display_username'),
      emailVerified: _authBool(
        json,
        'emailVerified',
        fallbackKey: 'email_verified',
      ),
      image: _authString(json, 'image'),
      role: _authString(json, 'role'),
      banned: _authBool(json, 'banned'),
      banReason: _authString(json, 'banReason', 'ban_reason'),
      banExpires: _authDateTime(json, 'banExpires', fallbackKey: 'ban_expires'),
      twoFactorEnabled: _authBool(
        json,
        'twoFactorEnabled',
        fallbackKey: 'two_factor_enabled',
      ),
      metadata: _authJsonValue(_authJsonLookup(json, 'metadata')),
      createdAt: _authRequiredDateTime(
        json,
        'createdAt',
        fallbackKey: 'created_at',
      ),
      updatedAt: _authRequiredDateTime(
        json,
        'updatedAt',
        fallbackKey: 'updated_at',
      ),
    );
  }

  static const schemaId = 'DartEdgeAuthUser';

  static const schemaRef = JsonSchema.componentRef(schemaId);

  static const jsonSchema = JsonSchema.object(
    id: schemaId,
    properties: <String, JsonSchema>{
      'id': JsonSchema.string(),
      'name': JsonSchema.string(nullable: true),
      'email': JsonSchema.string(nullable: true),
      'emailVerified': JsonSchema.boolean(),
      'image': JsonSchema.string(nullable: true),
      'createdAt': JsonSchema.string(format: 'date-time'),
      'updatedAt': JsonSchema.string(format: 'date-time'),
      'username': JsonSchema.string(nullable: true),
      'displayUsername': JsonSchema.string(nullable: true),
      'twoFactorEnabled': JsonSchema.boolean(),
      'role': JsonSchema.string(nullable: true),
      'banned': JsonSchema.boolean(),
      'banReason': JsonSchema.string(nullable: true),
      'banExpires': JsonSchema.string(nullable: true, format: 'date-time'),
    },
    required: <String>[
      'id',
      'name',
      'email',
      'emailVerified',
      'image',
      'createdAt',
      'updatedAt',
      'username',
      'displayUsername',
      'twoFactorEnabled',
      'role',
      'banned',
      'banReason',
      'banExpires',
    ],
    additionalProperties: false,
  );

  final String id;
  final String? name;
  final String? email;
  final String? username;
  final String? displayUsername;
  final bool emailVerified;
  final String? image;
  final String? role;
  final bool banned;
  final String? banReason;
  final DateTime? banExpires;
  final bool twoFactorEnabled;
  final Object? metadata;
  final DateTime createdAt;
  final DateTime updatedAt;

  Map<String, Object?> toColumns() => <String, Object?>{
    'id': id,
    'name': name,
    'email': email,
    'username': username,
    'display_username': displayUsername,
    'email_verified': emailVerified,
    'image': image,
    'role': role,
    'banned': banned,
    'ban_reason': banReason,
    'ban_expires': banExpires?.toIso8601String(),
    'two_factor_enabled': twoFactorEnabled,
    'metadata': _authJsonColumn(metadata),
    'created_at': createdAt.toIso8601String(),
    'updated_at': updatedAt.toIso8601String(),
  };

  @override
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'name': name,
    'email': email,
    'emailVerified': emailVerified,
    'image': image,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
    'username': username,
    'displayUsername': displayUsername,
    'twoFactorEnabled': twoFactorEnabled,
    'role': role,
    'banned': banned,
    'banReason': banReason,
    'banExpires': banExpires?.toIso8601String(),
  };

  @override
  String toString() {
    return 'DartEdgeAuthUser(id: $id, email: $email, role: $role)';
  }
}
''';

const _sessionModel = r'''
// Generated by tool/generate_auth_models.dart from the Better Auth SQL schema.
// Do not edit by hand.

part of '../../dart_edge_auth.dart';

/// Row model for the Better Auth `sessions` table.
final class DartEdgeAuthSession implements JsonEncodable {
  const DartEdgeAuthSession({
    required this.id,
    required this.userId,
    required this.token,
    required this.ipAddress,
    required this.userAgent,
    required this.expiresAt,
    required this.activeOrganizationId,
    required this.impersonatedBy,
    required this.active,
    required this.createdAt,
    required this.updatedAt,
  });

  factory DartEdgeAuthSession.fromSqlRow(SqlRow row, {String prefix = ''}) {
    return DartEdgeAuthSession(
      id: row.read<String>('${prefix}id'),
      userId: row.read<String>('${prefix}user_id'),
      token: row.read<String>('${prefix}token'),
      ipAddress: row.readNullable<String>('${prefix}ip_address'),
      userAgent: row.readNullable<String>('${prefix}user_agent'),
      expiresAt: _authRequiredDateTimeValue(row['${prefix}expires_at']),
      activeOrganizationId: row.readNullable<String>(
        '${prefix}active_organization_id',
      ),
      impersonatedBy: row.readNullable<String>('${prefix}impersonated_by'),
      active: _authBoolValue(row['${prefix}active'], defaultValue: true),
      createdAt: _authRequiredDateTimeValue(row['${prefix}created_at']),
      updatedAt: _authRequiredDateTimeValue(row['${prefix}updated_at']),
    );
  }

  factory DartEdgeAuthSession.fromColumns(
    Map<String, Object?> columns, {
    String prefix = '',
  }) => DartEdgeAuthSession.fromSqlRow(SqlRow(columns), prefix: prefix);

  factory DartEdgeAuthSession.fromJson(Map<String, Object?> json) {
    return DartEdgeAuthSession(
      id: _authRequiredString(json, 'id'),
      userId: _authRequiredString(json, 'userId', 'user_id'),
      token: _authRequiredString(json, 'token'),
      ipAddress: _authString(json, 'ipAddress', 'ip_address'),
      userAgent: _authString(json, 'userAgent', 'user_agent'),
      expiresAt: _authRequiredDateTime(
        json,
        'expiresAt',
        fallbackKey: 'expires_at',
      ),
      activeOrganizationId: _authString(
        json,
        'activeOrganizationId',
        'active_organization_id',
      ),
      impersonatedBy: _authString(json, 'impersonatedBy', 'impersonated_by'),
      active: _authBool(json, 'active', defaultValue: true),
      createdAt: _authRequiredDateTime(
        json,
        'createdAt',
        fallbackKey: 'created_at',
      ),
      updatedAt: _authRequiredDateTime(
        json,
        'updatedAt',
        fallbackKey: 'updated_at',
      ),
    );
  }

  static const schemaId = 'DartEdgeAuthSession';

  static const schemaRef = JsonSchema.componentRef(schemaId);

  static const jsonSchema = JsonSchema.object(
    id: schemaId,
    properties: <String, JsonSchema>{
      'id': JsonSchema.string(),
      'expiresAt': JsonSchema.string(format: 'date-time'),
      'token': JsonSchema.string(),
      'createdAt': JsonSchema.string(format: 'date-time'),
      'updatedAt': JsonSchema.string(format: 'date-time'),
      'ipAddress': JsonSchema.string(nullable: true),
      'userAgent': JsonSchema.string(nullable: true),
      'userId': JsonSchema.string(),
      'impersonatedBy': JsonSchema.string(nullable: true),
      'activeOrganizationId': JsonSchema.string(nullable: true),
    },
    required: <String>[
      'id',
      'expiresAt',
      'token',
      'createdAt',
      'updatedAt',
      'ipAddress',
      'userAgent',
      'userId',
      'impersonatedBy',
      'activeOrganizationId',
    ],
    additionalProperties: false,
  );

  final String id;
  final String userId;
  final String token;
  final String? ipAddress;
  final String? userAgent;
  final DateTime expiresAt;
  final String? activeOrganizationId;
  final String? impersonatedBy;
  final bool active;
  final DateTime createdAt;
  final DateTime updatedAt;

  Map<String, Object?> toColumns() => <String, Object?>{
    'id': id,
    'user_id': userId,
    'token': token,
    'ip_address': ipAddress,
    'user_agent': userAgent,
    'expires_at': expiresAt.toIso8601String(),
    'active_organization_id': activeOrganizationId,
    'impersonated_by': impersonatedBy,
    'active': active,
    'created_at': createdAt.toIso8601String(),
    'updated_at': updatedAt.toIso8601String(),
  };

  @override
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'expiresAt': expiresAt.toIso8601String(),
    'token': token,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
    'ipAddress': ipAddress,
    'userAgent': userAgent,
    'userId': userId,
    'impersonatedBy': impersonatedBy,
    'activeOrganizationId': activeOrganizationId,
  };

  @override
  String toString() {
    return 'DartEdgeAuthSession(id: $id, userId: $userId, active: $active)';
  }
}
''';
