import 'dart:io';

import 'package:dart_edge_sql/dart_edge_sql.dart';
import 'package:dart_edge_sql_codegen/dart_edge_sql_codegen.dart';

const _schemaPath =
    'rust/vendor/better-auth-diesel-sqlite/migrations/'
    '00000000000000_create_auth_tables/up.sql';

Future<void> main() async {
  final schema = File(_schemaPath).readAsStringSync();
  final database = await _introspectBetterAuthSchema(schema);

  final outputs = <String, String>{
    'lib/src/generated/schema.g.dart': _schema,
    'lib/src/generated/tables.g.dart': _emitTables(database),
  };

  for (final entry in outputs.entries) {
    final file = File(entry.key)..parent.createSync(recursive: true);
    file.writeAsStringSync(entry.value);
  }
}

Future<IntrospectedDatabase> _introspectBetterAuthSchema(String schema) async {
  final database = SqliteDatabase.inMemory();
  try {
    await database.execute(sql(schema));
    return await SqliteIntrospector.fromDatabase(
      database,
      includeTables: const {'users', 'sessions'},
    ).introspect();
  } finally {
    await database.close();
  }
}

String _emitTables(IntrospectedDatabase database) {
  return emitDartTableModelLibrary(
    database,
    naming: DartSchemaNaming(modelNameBuilder: _authModelName),
  );
}

String _authModelName(DartSchemaModelNameContext context) {
  final tablePrefix = switch (context.tableName) {
    'users' => 'DartEdgeAuthUser',
    'sessions' => 'DartEdgeAuthSession',
    final table => throw StateError('Unsupported Better Auth table "$table".'),
  };
  return switch (context.kind) {
    DartSchemaModelKind.row => '${tablePrefix}Row',
    DartSchemaModelKind.insert => '${tablePrefix}Insert',
    DartSchemaModelKind.update => '${tablePrefix}Update',
    DartSchemaModelKind.table => '${tablePrefix}sTable',
  };
}

const _schema = r'''
// Generated by tool/generate_auth_models.dart from the Better Auth SQL schema.
// Do not edit by hand.

part of '../dart_edge_auth.dart';

/// Generated route result schema registry and table descriptors for Better Auth.
final class DartEdgeAuthSchema {
  const DartEdgeAuthSchema({this.databaseSchema});

  /// Optional database schema that contains the Better Auth tables.
  final String? databaseSchema;

  static const users = DartEdgeAuthUsersTable.table;
  static const sessions = DartEdgeAuthSessionsTable.table;

  static const List<JsonSchema> modelSchemas = <JsonSchema>[
    DartEdgeAuthUser.jsonSchema,
    DartEdgeAuthSession.jsonSchema,
  ];

  static const List<JsonSchema> resultSchemas = <JsonSchema>[
    DartEdgeAuthSignUpResult.jsonSchema,
    DartEdgeAuthSignInResult.jsonSchema,
    DartEdgeAuthSessionResult.jsonSchema,
    DartEdgeAuthUserResult.jsonSchema,
    DartEdgeAuthSessionUserResult.jsonSchema,
    DartEdgeAuthListUsersResult.jsonSchema,
    DartEdgeAuthListSessionsResult.jsonSchema,
    DartEdgeAuthStatusResult.jsonSchema,
    DartEdgeAuthSuccessResult.jsonSchema,
    DartEdgeAuthPermissionResult.jsonSchema,
  ];

  static const List<JsonSchema> schemas = <JsonSchema>[
    ...modelSchemas,
    ...resultSchemas,
  ];

  static const JsonSchemaRegistry jsonSchemas = JsonSchemaRegistry(
    schemas: schemas,
  );
}

extension DartEdgeAuthSchemaTables on DartEdgeAuthSchema {
  DartEdgeAuthSessionsTable get sessions =>
      DartEdgeAuthSessionsTable.withSchema(databaseSchema);

  DartEdgeAuthUsersTable get users =>
      DartEdgeAuthUsersTable.withSchema(databaseSchema);
}
''';
