import 'dart:io';

const _schemaPath =
    'rust/vendor/better-auth-diesel-sqlite/migrations/'
    '00000000000000_create_auth_tables/up.sql';

const _outputs = <String, String>{
  'lib/src/generated/model_helpers.g.dart': _modelHelpers,
  'lib/src/generated/schema.g.dart': _schema,
  'lib/src/generated/models/user.g.dart': _userModel,
  'lib/src/generated/models/session.g.dart': _sessionModel,
};

void main() {
  final schema = File(_schemaPath).readAsStringSync();
  _assertColumns(schema, 'users', const [
    'id',
    'name',
    'email',
    'username',
    'display_username',
    'email_verified',
    'image',
    'role',
    'banned',
    'ban_reason',
    'ban_expires',
    'two_factor_enabled',
    'metadata',
    'created_at',
    'updated_at',
  ]);
  _assertColumns(schema, 'sessions', const [
    'id',
    'user_id',
    'token',
    'ip_address',
    'user_agent',
    'expires_at',
    'active_organization_id',
    'impersonated_by',
    'active',
    'created_at',
    'updated_at',
  ]);

  for (final entry in _outputs.entries) {
    final file = File(entry.key)..parent.createSync(recursive: true);
    file.writeAsStringSync(entry.value);
  }
}

void _assertColumns(String schema, String tableName, List<String> columns) {
  final table = RegExp(
    'CREATE TABLE IF NOT EXISTS "$tableName" \\((.*?)\\);',
    dotAll: true,
  ).firstMatch(schema);
  if (table == null) {
    throw StateError('Missing Better Auth SQL table "$tableName".');
  }

  final body = table[1]!;
  final actual = RegExp(
    r'^\s+"?([A-Za-z_][A-Za-z0-9_]*)"?\s+',
    multiLine: true,
  ).allMatches(body).map((match) => match[1]!).toSet();
  for (final column in columns) {
    if (!actual.contains(column)) {
      throw StateError('Missing Better Auth SQL column "$tableName.$column".');
    }
  }
}

const _modelHelpers = r'''
// Generated by tool/generate_auth_models.dart from the Better Auth SQL schema.
// Do not edit by hand.

part of '../dart_edge_auth.dart';

Object? _authJsonLookup(Map<String, Object?> json, String key, [String? alt]) {
  if (json.containsKey(key)) {
    return json[key];
  }
  if (alt != null && json.containsKey(alt)) {
    return json[alt];
  }
  return null;
}

String _authRequiredString(
  Map<String, Object?> json,
  String key, [
  String? alt,
]) {
  final value = _authJsonLookup(json, key, alt);
  if (value is String) {
    return value;
  }
  throw StateError('Auth JSON field "$key" is not a string.');
}

String? _authString(Map<String, Object?> json, String key, [String? alt]) {
  final value = _authJsonLookup(json, key, alt);
  if (value == null) {
    return null;
  }
  if (value is String) {
    return value;
  }
  throw StateError('Auth JSON field "$key" is not a string.');
}

bool _authBool(
  Map<String, Object?> json,
  String key, {
  String? fallbackKey,
  bool defaultValue = false,
}) {
  final value = _authJsonLookup(json, key, fallbackKey);
  return _authBoolValue(value, defaultValue: defaultValue);
}

bool _authBoolValue(Object? value, {bool defaultValue = false}) {
  return switch (value) {
    null => defaultValue,
    final bool boolValue => boolValue,
    final num number => number != 0,
    final String text => text == '1' || text.toLowerCase() == 'true',
    _ => throw StateError('Auth value "$value" is not a boolean.'),
  };
}

DateTime _authRequiredDateTime(
  Map<String, Object?> json,
  String key, {
  String? fallbackKey,
}) {
  final value = _authJsonLookup(json, key, fallbackKey);
  return _authRequiredDateTimeValue(value);
}

DateTime _authRequiredDateTimeValue(Object? value) {
  final parsed = _authDateTimeValue(value);
  if (parsed == null) {
    throw StateError('Auth date-time value is missing.');
  }
  return parsed;
}

DateTime? _authDateTime(
  Map<String, Object?> json,
  String key, {
  String? fallbackKey,
}) {
  return _authDateTimeValue(_authJsonLookup(json, key, fallbackKey));
}

DateTime? _authDateTimeValue(Object? value) {
  return switch (value) {
    null => null,
    final DateTime dateTime => dateTime,
    final String text when text.isEmpty => null,
    final String text => DateTime.parse(text),
    _ => throw StateError('Auth value "$value" is not a date-time.'),
  };
}

Object? _authJsonValue(Object? value) {
  if (value is String) {
    final trimmed = value.trimLeft();
    if (trimmed.startsWith('{') || trimmed.startsWith('[')) {
      return jsonDecode(value);
    }
  }
  return value;
}

Object? _authJsonColumn(Object? value) {
  if (value == null || value is String) {
    return value;
  }
  return jsonEncode(value);
}
''';

const _schema = r'''
// Generated by tool/generate_auth_models.dart from the Better Auth SQL schema.
// Do not edit by hand.

part of '../dart_edge_auth.dart';

/// Generated model, route result schema, and table descriptors for Better Auth.
final class DartEdgeAuthSchema {
  const DartEdgeAuthSchema._();

  static const users = DartEdgeAuthUsersTable.table;
  static const sessions = DartEdgeAuthSessionsTable.table;

  static const List<JsonSchema> modelSchemas = <JsonSchema>[
    DartEdgeAuthUser.jsonSchema,
    DartEdgeAuthSession.jsonSchema,
  ];

  static const List<JsonSchema> resultSchemas = <JsonSchema>[
    DartEdgeAuthSignUpResult.jsonSchema,
    DartEdgeAuthSignInResult.jsonSchema,
    DartEdgeAuthSessionResult.jsonSchema,
    DartEdgeAuthUserResult.jsonSchema,
    DartEdgeAuthSessionUserResult.jsonSchema,
    DartEdgeAuthListUsersResult.jsonSchema,
    DartEdgeAuthListSessionsResult.jsonSchema,
    DartEdgeAuthStatusResult.jsonSchema,
    DartEdgeAuthSuccessResult.jsonSchema,
    DartEdgeAuthPermissionResult.jsonSchema,
  ];

  static const List<JsonSchema> schemas = <JsonSchema>[
    ...modelSchemas,
    ...resultSchemas,
  ];

  static const JsonSchemaRegistry jsonSchemas = JsonSchemaRegistry(
    schemas: schemas,
  );
}
''';

const _userModel = r'''
// Generated by tool/generate_auth_models.dart from the Better Auth SQL schema.
// Do not edit by hand.

part of '../../dart_edge_auth.dart';

/// Row model for the Better Auth `users` table.
final class DartEdgeAuthUser implements JsonEncodable {
  const DartEdgeAuthUser({
    required this.id,
    required this.name,
    required this.email,
    required this.username,
    required this.displayUsername,
    required this.emailVerified,
    required this.image,
    required this.role,
    required this.banned,
    required this.banReason,
    required this.banExpires,
    required this.twoFactorEnabled,
    required this.metadata,
    required this.createdAt,
    required this.updatedAt,
  });

  factory DartEdgeAuthUser.fromSqlRow(SqlRow row, {String prefix = ''}) {
    return DartEdgeAuthUser(
      id: row.read<String>('${prefix}id'),
      name: row.readNullable<String>('${prefix}name'),
      email: row.readNullable<String>('${prefix}email'),
      username: row.readNullable<String>('${prefix}username'),
      displayUsername: row.readNullable<String>('${prefix}display_username'),
      emailVerified: _authBoolValue(row['${prefix}email_verified']),
      image: row.readNullable<String>('${prefix}image'),
      role: row.readNullable<String>('${prefix}role'),
      banned: _authBoolValue(row['${prefix}banned']),
      banReason: row.readNullable<String>('${prefix}ban_reason'),
      banExpires: _authDateTimeValue(row['${prefix}ban_expires']),
      twoFactorEnabled: _authBoolValue(row['${prefix}two_factor_enabled']),
      metadata: _authJsonValue(row['${prefix}metadata']),
      createdAt: _authRequiredDateTimeValue(row['${prefix}created_at']),
      updatedAt: _authRequiredDateTimeValue(row['${prefix}updated_at']),
    );
  }

  factory DartEdgeAuthUser.fromColumns(
    Map<String, Object?> columns, {
    String prefix = '',
  }) => DartEdgeAuthUser.fromSqlRow(SqlRow(columns), prefix: prefix);

  factory DartEdgeAuthUser.fromJson(Map<String, Object?> json) {
    return DartEdgeAuthUser(
      id: _authRequiredString(json, 'id'),
      name: _authString(json, 'name'),
      email: _authString(json, 'email'),
      username: _authString(json, 'username'),
      displayUsername: _authString(json, 'displayUsername', 'display_username'),
      emailVerified: _authBool(
        json,
        'emailVerified',
        fallbackKey: 'email_verified',
      ),
      image: _authString(json, 'image'),
      role: _authString(json, 'role'),
      banned: _authBool(json, 'banned'),
      banReason: _authString(json, 'banReason', 'ban_reason'),
      banExpires: _authDateTime(json, 'banExpires', fallbackKey: 'ban_expires'),
      twoFactorEnabled: _authBool(
        json,
        'twoFactorEnabled',
        fallbackKey: 'two_factor_enabled',
      ),
      metadata: _authJsonValue(_authJsonLookup(json, 'metadata')),
      createdAt: _authRequiredDateTime(
        json,
        'createdAt',
        fallbackKey: 'created_at',
      ),
      updatedAt: _authRequiredDateTime(
        json,
        'updatedAt',
        fallbackKey: 'updated_at',
      ),
    );
  }

  static const schemaId = 'DartEdgeAuthUser';

  static const schemaRef = JsonSchema.ref(schemaId);

  static const jsonSchema = JsonSchema.object(
    id: schemaId,
    properties: <String, JsonSchema>{
      'id': JsonSchema.string(),
      'name': JsonSchema.string(nullable: true),
      'email': JsonSchema.string(nullable: true),
      'emailVerified': JsonSchema.boolean(),
      'image': JsonSchema.string(nullable: true),
      'createdAt': JsonSchema.string(format: 'date-time'),
      'updatedAt': JsonSchema.string(format: 'date-time'),
      'username': JsonSchema.string(nullable: true),
      'displayUsername': JsonSchema.string(nullable: true),
      'twoFactorEnabled': JsonSchema.boolean(),
      'role': JsonSchema.string(nullable: true),
      'banned': JsonSchema.boolean(),
      'banReason': JsonSchema.string(nullable: true),
      'banExpires': JsonSchema.string(nullable: true, format: 'date-time'),
    },
    required: <String>[
      'id',
      'name',
      'email',
      'emailVerified',
      'image',
      'createdAt',
      'updatedAt',
      'username',
      'displayUsername',
      'twoFactorEnabled',
      'role',
      'banned',
      'banReason',
      'banExpires',
    ],
    additionalProperties: false,
  );

  final String id;
  final String? name;
  final String? email;
  final String? username;
  final String? displayUsername;
  final bool emailVerified;
  final String? image;
  final String? role;
  final bool banned;
  final String? banReason;
  final DateTime? banExpires;
  final bool twoFactorEnabled;
  final Object? metadata;
  final DateTime createdAt;
  final DateTime updatedAt;

  Map<String, Object?> toColumns() => <String, Object?>{
    'id': id,
    'name': name,
    'email': email,
    'username': username,
    'display_username': displayUsername,
    'email_verified': emailVerified,
    'image': image,
    'role': role,
    'banned': banned,
    'ban_reason': banReason,
    'ban_expires': banExpires?.toIso8601String(),
    'two_factor_enabled': twoFactorEnabled,
    'metadata': _authJsonColumn(metadata),
    'created_at': createdAt.toIso8601String(),
    'updated_at': updatedAt.toIso8601String(),
  };

  @override
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'name': name,
    'email': email,
    'emailVerified': emailVerified,
    'image': image,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
    'username': username,
    'displayUsername': displayUsername,
    'twoFactorEnabled': twoFactorEnabled,
    'role': role,
    'banned': banned,
    'banReason': banReason,
    'banExpires': banExpires?.toIso8601String(),
  };

  @override
  String toString() {
    return 'DartEdgeAuthUser(id: $id, email: $email, role: $role)';
  }
}

/// Table descriptor for the Better Auth `users` table.
final class DartEdgeAuthUsersTable
    extends
        SqlTable<
          DartEdgeAuthUser,
          Map<String, Object?>,
          Map<String, Object?>
        > {
  const DartEdgeAuthUsersTable._();

  static const table = DartEdgeAuthUsersTable._();

  static final id = SqlColumn<String>(
    table: table,
    name: 'id',
    nullable: false,
  );
  static final nameColumn = SqlColumn<String>(
    table: table,
    name: 'name',
    nullable: true,
  );
  static final email = SqlColumn<String>(
    table: table,
    name: 'email',
    nullable: false,
  );
  static final username = SqlColumn<String>(
    table: table,
    name: 'username',
    nullable: true,
  );
  static final displayUsername = SqlColumn<String>(
    table: table,
    name: 'display_username',
    nullable: true,
  );
  static final emailVerified = SqlColumn<bool>(
    table: table,
    name: 'email_verified',
    nullable: false,
  );
  static final image = SqlColumn<String>(
    table: table,
    name: 'image',
    nullable: true,
  );
  static final role = SqlColumn<String>(
    table: table,
    name: 'role',
    nullable: false,
  );
  static final banned = SqlColumn<bool>(
    table: table,
    name: 'banned',
    nullable: false,
  );
  static final banReason = SqlColumn<String>(
    table: table,
    name: 'ban_reason',
    nullable: true,
  );
  static final banExpires = SqlColumn<String>(
    table: table,
    name: 'ban_expires',
    nullable: true,
  );
  static final twoFactorEnabled = SqlColumn<bool>(
    table: table,
    name: 'two_factor_enabled',
    nullable: false,
  );
  static final metadata = SqlColumn<Object?>(
    table: table,
    name: 'metadata',
    nullable: true,
  );
  static final createdAt = SqlColumn<String>(
    table: table,
    name: 'created_at',
    nullable: false,
  );
  static final updatedAt = SqlColumn<String>(
    table: table,
    name: 'updated_at',
    nullable: false,
  );

  @override
  String get name => 'users';

  @override
  String? get schema => null;

  @override
  List<SqlColumn<Object?>> get columns => <SqlColumn<Object?>>[
    id.asObjectColumn,
    nameColumn.asObjectColumn,
    email.asObjectColumn,
    username.asObjectColumn,
    displayUsername.asObjectColumn,
    emailVerified.asObjectColumn,
    image.asObjectColumn,
    role.asObjectColumn,
    banned.asObjectColumn,
    banReason.asObjectColumn,
    banExpires.asObjectColumn,
    twoFactorEnabled.asObjectColumn,
    metadata.asObjectColumn,
    createdAt.asObjectColumn,
    updatedAt.asObjectColumn,
  ];

  @override
  DartEdgeAuthUser mapRow(SqlRow row, {String prefix = ''}) =>
      DartEdgeAuthUser.fromSqlRow(row, prefix: prefix);

  @override
  Map<String, Object?> encodeInsert(Map<String, Object?> value) => value;

  @override
  Map<String, Object?> encodeUpdate(Map<String, Object?> value) => value;
}
''';

const _sessionModel = r'''
// Generated by tool/generate_auth_models.dart from the Better Auth SQL schema.
// Do not edit by hand.

part of '../../dart_edge_auth.dart';

/// Row model for the Better Auth `sessions` table.
final class DartEdgeAuthSession implements JsonEncodable {
  const DartEdgeAuthSession({
    required this.id,
    required this.userId,
    required this.token,
    required this.ipAddress,
    required this.userAgent,
    required this.expiresAt,
    required this.activeOrganizationId,
    required this.impersonatedBy,
    required this.active,
    required this.createdAt,
    required this.updatedAt,
  });

  factory DartEdgeAuthSession.fromSqlRow(SqlRow row, {String prefix = ''}) {
    return DartEdgeAuthSession(
      id: row.read<String>('${prefix}id'),
      userId: row.read<String>('${prefix}user_id'),
      token: row.read<String>('${prefix}token'),
      ipAddress: row.readNullable<String>('${prefix}ip_address'),
      userAgent: row.readNullable<String>('${prefix}user_agent'),
      expiresAt: _authRequiredDateTimeValue(row['${prefix}expires_at']),
      activeOrganizationId: row.readNullable<String>(
        '${prefix}active_organization_id',
      ),
      impersonatedBy: row.readNullable<String>('${prefix}impersonated_by'),
      active: _authBoolValue(row['${prefix}active'], defaultValue: true),
      createdAt: _authRequiredDateTimeValue(row['${prefix}created_at']),
      updatedAt: _authRequiredDateTimeValue(row['${prefix}updated_at']),
    );
  }

  factory DartEdgeAuthSession.fromColumns(
    Map<String, Object?> columns, {
    String prefix = '',
  }) => DartEdgeAuthSession.fromSqlRow(SqlRow(columns), prefix: prefix);

  factory DartEdgeAuthSession.fromJson(Map<String, Object?> json) {
    return DartEdgeAuthSession(
      id: _authRequiredString(json, 'id'),
      userId: _authRequiredString(json, 'userId', 'user_id'),
      token: _authRequiredString(json, 'token'),
      ipAddress: _authString(json, 'ipAddress', 'ip_address'),
      userAgent: _authString(json, 'userAgent', 'user_agent'),
      expiresAt: _authRequiredDateTime(
        json,
        'expiresAt',
        fallbackKey: 'expires_at',
      ),
      activeOrganizationId: _authString(
        json,
        'activeOrganizationId',
        'active_organization_id',
      ),
      impersonatedBy: _authString(json, 'impersonatedBy', 'impersonated_by'),
      active: _authBool(json, 'active', defaultValue: true),
      createdAt: _authRequiredDateTime(
        json,
        'createdAt',
        fallbackKey: 'created_at',
      ),
      updatedAt: _authRequiredDateTime(
        json,
        'updatedAt',
        fallbackKey: 'updated_at',
      ),
    );
  }

  static const schemaId = 'DartEdgeAuthSession';

  static const schemaRef = JsonSchema.ref(schemaId);

  static const jsonSchema = JsonSchema.object(
    id: schemaId,
    properties: <String, JsonSchema>{
      'id': JsonSchema.string(),
      'expiresAt': JsonSchema.string(format: 'date-time'),
      'token': JsonSchema.string(),
      'createdAt': JsonSchema.string(format: 'date-time'),
      'updatedAt': JsonSchema.string(format: 'date-time'),
      'ipAddress': JsonSchema.string(nullable: true),
      'userAgent': JsonSchema.string(nullable: true),
      'userId': JsonSchema.string(),
      'impersonatedBy': JsonSchema.string(nullable: true),
      'activeOrganizationId': JsonSchema.string(nullable: true),
    },
    required: <String>[
      'id',
      'expiresAt',
      'token',
      'createdAt',
      'updatedAt',
      'ipAddress',
      'userAgent',
      'userId',
      'impersonatedBy',
      'activeOrganizationId',
    ],
    additionalProperties: false,
  );

  final String id;
  final String userId;
  final String token;
  final String? ipAddress;
  final String? userAgent;
  final DateTime expiresAt;
  final String? activeOrganizationId;
  final String? impersonatedBy;
  final bool active;
  final DateTime createdAt;
  final DateTime updatedAt;

  Map<String, Object?> toColumns() => <String, Object?>{
    'id': id,
    'user_id': userId,
    'token': token,
    'ip_address': ipAddress,
    'user_agent': userAgent,
    'expires_at': expiresAt.toIso8601String(),
    'active_organization_id': activeOrganizationId,
    'impersonated_by': impersonatedBy,
    'active': active,
    'created_at': createdAt.toIso8601String(),
    'updated_at': updatedAt.toIso8601String(),
  };

  @override
  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'expiresAt': expiresAt.toIso8601String(),
    'token': token,
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
    'ipAddress': ipAddress,
    'userAgent': userAgent,
    'userId': userId,
    'impersonatedBy': impersonatedBy,
    'activeOrganizationId': activeOrganizationId,
  };

  @override
  String toString() {
    return 'DartEdgeAuthSession(id: $id, userId: $userId, active: $active)';
  }
}

/// Table descriptor for the Better Auth `sessions` table.
final class DartEdgeAuthSessionsTable
    extends
        SqlTable<
          DartEdgeAuthSession,
          Map<String, Object?>,
          Map<String, Object?>
        > {
  const DartEdgeAuthSessionsTable._();

  static const table = DartEdgeAuthSessionsTable._();

  static final id = SqlColumn<String>(
    table: table,
    name: 'id',
    nullable: false,
  );
  static final userId = SqlColumn<String>(
    table: table,
    name: 'user_id',
    nullable: false,
  );
  static final token = SqlColumn<String>(
    table: table,
    name: 'token',
    nullable: false,
  );
  static final ipAddress = SqlColumn<String>(
    table: table,
    name: 'ip_address',
    nullable: true,
  );
  static final userAgent = SqlColumn<String>(
    table: table,
    name: 'user_agent',
    nullable: true,
  );
  static final expiresAt = SqlColumn<String>(
    table: table,
    name: 'expires_at',
    nullable: false,
  );
  static final activeOrganizationId = SqlColumn<String>(
    table: table,
    name: 'active_organization_id',
    nullable: true,
  );
  static final impersonatedBy = SqlColumn<String>(
    table: table,
    name: 'impersonated_by',
    nullable: true,
  );
  static final active = SqlColumn<bool>(
    table: table,
    name: 'active',
    nullable: false,
  );
  static final createdAt = SqlColumn<String>(
    table: table,
    name: 'created_at',
    nullable: false,
  );
  static final updatedAt = SqlColumn<String>(
    table: table,
    name: 'updated_at',
    nullable: false,
  );

  @override
  String get name => 'sessions';

  @override
  String? get schema => null;

  @override
  List<SqlColumn<Object?>> get columns => <SqlColumn<Object?>>[
    id.asObjectColumn,
    userId.asObjectColumn,
    token.asObjectColumn,
    ipAddress.asObjectColumn,
    userAgent.asObjectColumn,
    expiresAt.asObjectColumn,
    activeOrganizationId.asObjectColumn,
    impersonatedBy.asObjectColumn,
    active.asObjectColumn,
    createdAt.asObjectColumn,
    updatedAt.asObjectColumn,
  ];

  @override
  DartEdgeAuthSession mapRow(SqlRow row, {String prefix = ''}) =>
      DartEdgeAuthSession.fromSqlRow(row, prefix: prefix);

  @override
  Map<String, Object?> encodeInsert(Map<String, Object?> value) => value;

  @override
  Map<String, Object?> encodeUpdate(Map<String, Object?> value) => value;
}
''';
