// ignore_for_file: camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset('package:dart_edge_audio/dart_edge_audio.dart')
library;

import 'dart:ffi' as ffi;
import 'package:dart_edge_native_bridge/dart_edge_native_bridge.dart' as imp$1;

@ffi.Native<
  ffi.Pointer<NativeAudioBytesResult> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
  )
>()
external ffi.Pointer<NativeAudioBytesResult> dart_edge_audio_convert_bytes(
  ffi.Pointer<ffi.Char> request_json,
  ffi.Pointer<ffi.Uint8> input_ptr,
  int input_len,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> dart_edge_audio_convert_file(
  ffi.Pointer<ffi.Char> request_json,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeAudioStreamResult>)>()
external void dart_edge_audio_dispose_stream_result(
  ffi.Pointer<NativeAudioStreamResult> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeAudioBytesResult>)>(
  isLeaf: true,
)
external void dart_edge_audio_free_bytes_result(
  ffi.Pointer<NativeAudioBytesResult> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<NativeAudioStreamResult>)>()
external void dart_edge_audio_free_stream_result(
  ffi.Pointer<NativeAudioStreamResult> value,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>(isLeaf: true)
external void dart_edge_audio_free_string(ffi.Pointer<ffi.Char> value);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Void>)>()
external int dart_edge_audio_initialize_dart_api_dl(ffi.Pointer<ffi.Void> data);

@ffi.Native<ffi.Int32 Function()>(isLeaf: true)
external int dart_edge_audio_native_abi_version();

@ffi.Native<
  ffi.Pointer<DartEdgeAudioPool> Function(ffi.UintPtr, ffi.UintPtr, ffi.Int64)
>()
external ffi.Pointer<DartEdgeAudioPool> dart_edge_audio_pool_create(
  int worker_count,
  int max_queue_size,
  int completion_port,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<DartEdgeAudioPool>)>()
external void dart_edge_audio_pool_free(ffi.Pointer<DartEdgeAudioPool> pool);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<DartEdgeAudioPool>)>()
external ffi.Pointer<ffi.Char> dart_edge_audio_pool_metrics(
  ffi.Pointer<DartEdgeAudioPool> pool,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<DartEdgeAudioPool>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<NativeAudioStreamInput>,
    ffi.IntPtr,
  )
>()
external int dart_edge_audio_pool_submit_concatenate_streams(
  ffi.Pointer<DartEdgeAudioPool> pool,
  ffi.Pointer<ffi.Char> request_json,
  ffi.Pointer<NativeAudioStreamInput> inputs,
  int input_count,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<DartEdgeAudioPool>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
  )
>()
external int dart_edge_audio_pool_submit_convert_bytes(
  ffi.Pointer<DartEdgeAudioPool> pool,
  ffi.Pointer<ffi.Char> request_json,
  ffi.Pointer<ffi.Uint8> input_ptr,
  int input_len,
);

@ffi.Native<
  ffi.Int64 Function(ffi.Pointer<DartEdgeAudioPool>, ffi.Pointer<ffi.Char>)
>()
external int dart_edge_audio_pool_submit_convert_file(
  ffi.Pointer<DartEdgeAudioPool> pool,
  ffi.Pointer<ffi.Char> request_json,
);

@ffi.Native<
  ffi.Int64 Function(
    ffi.Pointer<DartEdgeAudioPool>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
  )
>()
external int dart_edge_audio_pool_submit_probe_bytes(
  ffi.Pointer<DartEdgeAudioPool> pool,
  ffi.Pointer<ffi.Char> options_json,
  ffi.Pointer<ffi.Uint8> input_ptr,
  int input_len,
);

@ffi.Native<
  ffi.Int64 Function(ffi.Pointer<DartEdgeAudioPool>, ffi.Pointer<ffi.Char>)
>()
external int dart_edge_audio_pool_submit_probe_file(
  ffi.Pointer<DartEdgeAudioPool> pool,
  ffi.Pointer<ffi.Char> request_json,
);

@ffi.Native<
  ffi.Pointer<NativeAudioBytesResult> Function(
    ffi.Pointer<DartEdgeAudioPool>,
    ffi.Int64,
  )
>()
external ffi.Pointer<NativeAudioBytesResult>
dart_edge_audio_pool_take_convert_result(
  ffi.Pointer<DartEdgeAudioPool> pool,
  int job_id,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<DartEdgeAudioPool>, ffi.Int64)
>()
external ffi.Pointer<ffi.Char> dart_edge_audio_pool_take_file_result(
  ffi.Pointer<DartEdgeAudioPool> pool,
  int job_id,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(ffi.Pointer<DartEdgeAudioPool>, ffi.Int64)
>()
external ffi.Pointer<ffi.Char> dart_edge_audio_pool_take_probe_result(
  ffi.Pointer<DartEdgeAudioPool> pool,
  int job_id,
);

@ffi.Native<
  ffi.Pointer<NativeAudioStreamResult> Function(
    ffi.Pointer<DartEdgeAudioPool>,
    ffi.Int64,
  )
>()
external ffi.Pointer<NativeAudioStreamResult>
dart_edge_audio_pool_take_stream_result(
  ffi.Pointer<DartEdgeAudioPool> pool,
  int job_id,
);

@ffi.Native<
  ffi.Pointer<ffi.Char> Function(
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Uint8>,
    ffi.IntPtr,
  )
>()
external ffi.Pointer<ffi.Char> dart_edge_audio_probe_bytes(
  ffi.Pointer<ffi.Char> options_json,
  ffi.Pointer<ffi.Uint8> input_ptr,
  int input_len,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<ffi.Char>)>()
external ffi.Pointer<ffi.Char> dart_edge_audio_probe_file(
  ffi.Pointer<ffi.Char> path,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> dart_edge_audio_take_last_error();

final class DartEdgeAudioPool extends ffi.Opaque {}

final class NativeAudioBytesResult extends ffi.Struct {
  external imp$1.NativeOwnedBytes bytes;

  external ffi.Pointer<ffi.Char> result_json;
}

final class NativeAudioStreamInput extends ffi.Struct {
  external imp$1.NativeByteStream stream;

  external ffi.Pointer<ffi.Char> file_name_hint;

  external ffi.Pointer<ffi.Char> mime_type_hint;
}

final class NativeAudioStreamResult extends ffi.Struct {
  external imp$1.NativeByteStream stream;

  @ffi.Int64()
  external int content_length;

  external ffi.Pointer<ffi.Char> result_json;
}
