name: dart_edge_benchmark_runner
description: Benchmark runner for comparing Dart Edge against other Dart servers.
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.11.0 <4.0.0"

resolution: workspace

dependencies:
  dart_edge_benchmark_shared: 0.1.0

dev_dependencies:
  test: ^1.30.0
