name: dart_edge_benchmark_runner
description: Benchmark runner for comparing Dart Edge against other Dart servers.
publish_to: none
version: 0.2.1

environment:
  sdk: ">=3.12.0 <4.0.0"

resolution: workspace

dependencies:
dev_dependencies:
  test: ^1.30.0
