name: dart_edge_benchmark_dart_edge_http_server
description: Dart Edge benchmark target.
publish_to: none
version: 0.2.0

environment:
  sdk: ">=3.11.0 <4.0.0"

resolution: workspace

dependencies:
  dart_edge_http_server:
    hosted: "https://registry.hippolabs.org/pub/internal-pub/"
