name: dart_edge_http_server
description: App-facing HTTP server package for the Dart Edge monorepo.
version: 0.2.0
publish_to: "https://registry.hippolabs.org/pub/internal-pub/"
repository: https://github.com/flowhorn/dart_edge/tree/main/packages/dart_edge_http_server

environment:
  sdk: ">=3.11.0 <4.0.0"

resolution: workspace

dependencies:
  dart_edge_http_server_runtime: ^0.2.0

dev_dependencies:
  test: ^1.30.0
